export const FETCH_LOCATION = "FETCH_LOCATION";
export const FETCH_LOCATION_SUCCESS = "FETCH_LOCATION_SUCCESS";

export const FETCH_WEEK_WEATHERS_SUCCESS = "FETCH_WEEK_WEATHERS_SUCCESS";
export const FETCH_TODAY_WEATHERS_SUCCESS = "FETCH_TODAY_WEATHERS_SUCCESS";
